# Generated by Django 4.2.1 on 2023-05-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=50)),
                ('ciclo', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_usuario_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField()),
                ('hora_publicacion', models.TimeField()),
                ('imagen', models.ImageField(upload_to='')),
                ('contenido', models.CharField(max_length=400)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('fecha_mensaje', models.DateField()),
                ('hora_mensaje', models.TimeField()),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.conversacion')),
                ('id_user_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='persona1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcmfriends.usuario'),
        ),
    ]
